# run: conda env create --file environment.yml
# I've only checked with conda==4.3.25 so please update
# to this version if there's an error
name: celer-env

dependencies:
    - Cython>=0.26
    - ipython
    - matplotlib>=2.0.0
    - nose
    - numba>=0.41
    - numpy>=1.12
    - numpydoc
    - pytest
    - pytest-cov
    - scikit-learn>=0.20.1
    - scipy>=0.18.0
    - seaborn>=0.7
    - tqdm

    - pip:
        - "https://api.github.com/repos/choldgraf/download/zipball/master"
